name: 'PR Bundle Analyzer-111'

on: [pull_request]
jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Annotate PR
        uses: AkshaySharma-BharatPe/pr-metadata-actions@main
        with:
          target_folder: src/assets
          thrashold_size: 100
          token: ${{ secrets.GITHUB_TOKEN }}
