name: "Edit Package JSON"

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}

jobs:
  Calculate-Bundle-Difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"
      - uses: bharatpe/pr-bundle-analyzer@dev
        with:
          install_command: "yarn install"
          build_command: "yarn run build"
          build_path: "build/static"
          base_branch: ${{ github.base_ref }}
          head_branch: ${{ github.head_ref }}
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          file: package.json
          field: dependencies.testRepo
          value: git+https://${{ secrets.PAT_GITHUB_TOKEN }}@github.com/AkshaySharma-BharatPe/temp
