name: 'PR Bundle Analyzer-111'

on: [pull_request]
jobs:
  Calculate-Bundle-Difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
      - uses: AkshaySharma-BharatPe/asset-test@dev
        with:
          token: ${{ secrets.GITHUB_TOKEN }}