name: "Edit Package JSON"

on: [pull_request]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  Calculate-Bundle-Difference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "16.16.0"

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: "testtt"
