name: Calculate JS Bundle Size

on: [pull_request]
jobs:
  calculate-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.16.0'
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: 'yarn install'
          build_command: 'yarn run build'
          dist_path: 'build/static'
          token: ${{ secrets.GITHUB_TOKEN }}

