name: My Workflow

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "A initial message"
          if true; then
          echo "print true"
          else 
          echo "else inside"
          exit 1
      - run: echo "One last message"
