name: If Else Echo Run Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Run If Else Script
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Event was a push"
          else
            echo "Event was not a push"
          fi
